### ISSUE TITLE
Give us a level

### ISSUE THREAD

**Issue by maxglas** [Esri/devsummit-feedback#6]
Words can be so confusing. Sometimes - when reading the abstract of an workshop - you think you listen to a professional talk, but you realize after a few moments, that the talk is just for beginners.

It would be _so_ much better, if you have a level (beginners, advanced, professional) that characterizes the workshop a little bit. Sometimes I would like to hear more hardcore sessions and sometimes I just want to have a look into a new topic. It is that normal that I am a professional in one way and a beginner in another.

And that would not also save time for the listener, it would also helps the lecturer:
he has the chance to do a more professional session, he could presume that basics must not be explained, and he has the time to show more tipps and tricks.

So, please: Give us a level! :)

**Comment by hhkaos** [comment]
+1 :)

**Comment by JimBarry** [comment]
Thanks! We will add levels to sessions at future DevSummits. They can be tough to do however, since not everyone's view of beginner, intermediate, and advanced is the same. There's also the issue of whether or not the level applies to the topic or to the level of experience the audience has with the underlying technology. But we will do it next time, and at the same time we will use the session Description to give a better picture of what you can expect us to cover in the session.
