### ISSUE TITLE
Why is it so difficult for the ESRI JavaScript API's to implement kinetic panning?

### ISSUE THREAD

**Issue by MapsRus** [Esri/devsummit-feedback#7]
Why is it so difficult for the ESRI JavaScript API's to implement **kinetic panning**?  Silverlight and Flex did.  And, of course all other mainstream mapping libraries do as well (mentioning no names of course)!

**Comment by JimBarry** [comment]
Kinetic panning is a UI enhancement that the JS team here at Esri want to add soon; we just don't know when yet. For us it just comes down to resources, work priority, and interest from the developer community, rather than difficulty.

Until then, here is a project I came across with all the kinetic pan source code in there. Might be something you can make use of: https://github.com/rymor/esri-kinetic-panning

Also here are two entries on the ArcGIS Ideas site that you can vote up and promote:
http://ideas.arcgis.com/ideaView?id=08730000000bxHdAAI
http://ideas.arcgis.com/ideaView?id=08730000000bvKQAAY
